In [2]:
import pandas as pd

# 1. Chargement des données
df = pd.read_csv('../data/raw/NBA Finals and MVP.csv', encoding='latin1')

# 2. Aperçu des 5 premières lignes
print("--- APERÇU DES DONNÉES ---")
display(df.head())

# 3. Informations sur les colonnes (types, valeurs nulles)
print("\n--- INFOS SUR LE DATASET ---")
df.info()

# 4. Statistiques descriptives
print("\n--- STATISTIQUES ---")
display(df.describe(include='all'))

--- APERÇU DES DONNÉES ---

,Year,Western Champion,Eastern Champion,Result,NBA Champion,NBA Vice-Champion,Final Sweep ?,MVP Name,MVP Height (m),MVP Height (ft),MVP Position,MVP Team,MVP Nationality,MVP status
0,1951.0,Rochester Royals,New York Knicks,43,Rochester Royals,New York Knicks,False,Ed Macauley,2.03,6.08,Center,Boston Celtics,US,Not reached Final
1,1952.0,Minneapolis Lakers,New York Knicks,43,Minneapolis Lakers,New York Knicks,False,Paul Arizin,1.93,6.04,Forward,Philadelphia Warriors,US,Not reached Final
2,1953.0,Minneapolis Lakers,New York Knicks,41,Minneapolis Lakers,New York Knicks,False,George Mikan,2.08,6.82,Center,Minneapolis Lakers,US,Not reached Final
3,1954.0,Minneapolis Lakers,Syracuse Nationals,43,Minneapolis Lakers,Syracuse Nationals,False,B. Cousy,1.85,6.07,Guard,Boston Celtics,US,Champion
4,1955.0,Fort Wayne Pistons,Syracuse Nationals,34,Syracuse Nationals,Fort Wayne Pistons,False,B. Pettit,2.06,6.76,Forward,Saint Louis Hawks,US,Not reached Final

--- INFOS SUR LE DATASET ---
<class 'pandas.DataFrame'>
RangeIndex: 69 entries, 0 to 68
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               68 non-null     float64
 1   Western Champion   68 non-null     str
 2   Eastern Champion   68 non-null     str
 3   Result             68 non-null     str
 4   NBA Champion       68 non-null     str
 5   NBA Vice-Champion  68 non-null     str
 6   Final Sweep ?      68 non-null     object
 7   MVP Name           68 non-null     str
 8   MVP Height (m)     68 non-null     float64
 9   MVP Height (ft)    68 non-null     float64
 10  MVP Position       68 non-null     str
 11  MVP Team           68 non-null     str
 12  MVP Nationality    68 non-null     str
 13  MVP status         69 non-null     str
dtypes: float64(3), object(1), str(10)
memory usage: 7.7+ KB

--- STATISTIQUES ---

,Year,Western Champion,Eastern Champion,Result,NBA Champion,NBA Vice-Champion,Final Sweep ?,MVP Name,MVP Height (m),MVP Height (ft),MVP Position,MVP Team,MVP Nationality,MVP status
count,68.00000,68,68,68,68,68,68,68,68.000000,68.000000,68,68,68,69
unique,NaN,16,14,10,21,27,2,37,NaN,NaN,3,23,4,3
top,NaN,Los Angeles Lakers,Boston Celtics,24,Boston Celtics,Los Angeles Lakers,False,B. Russell,NaN,NaN,Center,Boston Celtics,US,Not reached Final
freq,NaN,25,21,13,17,14,59,5,NaN,NaN,28,12,64,36
mean,1984.50000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.047500,6.706029,NaN,NaN,NaN,NaN
std,19.77372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.088644,0.306819,NaN,NaN,NaN,NaN
min,1951.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.830000,6.000000,NaN,NaN,NaN,NaN
25%,1967.75000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.980000,6.500000,NaN,NaN,NaN,NaN
50%,1984.50000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.060000,6.760000,NaN,NaN,NaN,NaN
75%,2001.25000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.110000,6.920000,NaN,NaN,NaN,NaN
max,2018.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.180000,7.150000,NaN,NaN,NaN,NaN